@host = http://localhost:3001
@token = {{authentication.response.body.access_token}}

### Criar conta
POST {{host}}/accounts
Content-Type: application/json

{
  "name": "Felipe França",
  "email": "felipe@franca3.dev",
  "password": "felipe"
}

### Gerar token
# @name authentication
POST {{host}}/sessions
Content-Type: application/json

{
  "email": "felipe@franca3.dev",
  "password": "felipe"
}

### Criar pergunta
POST {{host}}/questions
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "o que há de novo pra hoje?",
  "content": "o que há de novo pra hoje ?"
}

### Listar perguntas
GET {{host}}/questions?page=1&limit=10
Authorization: Bearer {{token}}
