name: nest-clean-rocket-test

services:
  postgres-test:
    image: postgres:16-alpine
    container_name: nest-clean-rocket-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: nest_clean_rocket_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nest_clean_rocket_test']
      interval: 5s
      timeout: 5s
      retries: 5
